Feat/#18
Chance-Glance/server pull request #23
Opened 2024-10-10 05:07 UTC by nahyun0423

## 📄 PR 요약

축제 일정 조회 api를 작성했습니다.

## 📋 관련 이슈

 #18 

## 🛠️ 변경 사항 설명

자세하게 변경된 사항을 설명해주세요. 

## 📷 스크린샷

변경 사항을 시각적으로 보여주는 스크린샷을 첨부해주세요. 이미지를 첨부하는 방법은 다음과 같습니다:

## 📄 추가 정보

추가로 제공하고 싶은 정보가 있다면 작성해주세요. 
리뷰어들에게 꼼꼼하게 리뷰받고 싶은 부분이나, 구현하면서 어려웠던 부분,
구현하면서 새로 알게 된 부분 등등 리뷰어의 이해를 돕기 위해 필요한 내용을 적어주세요.

2024-10-10 08:58 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/application/FestivalDateService.java
> +public class FestivalDateService {
DIP 원칙을 적용하기 위해, 서비스 구현체를 추상화한 `UseCase` 인터페이스를 `domain-service` 패키지에 작성해주세요. 이후 `FestivalDateService`가 이 `UseCase` 인터페이스를 구현하도록 하면 됩니다.

이렇게 `DIP` 원칙을 준수하면, `Controller`가 `FestivalDateService`와 같은 구현체(저수준 모듈)에 의존하는 대신, `FestivalDateUseCase`와 같은 추상화된 고수준 모듈에 의존하게 됩니다. 이를 통해 코드 변경 시 더 유연하게 대처할 수 있는 장점을 가지게 됩니다. 따라서 이와 같은 방식을 권장드려요 :)

2024-10-10 08:58 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +    private final FestivalDateService festivalDateService;
이 부분 `FestivalDateService` 코멘트 남겨드린 것을 기반으로 하여, 구현체가 아닌 `UseCase` 인터페이스로 변경 부탁드릴게요!

2024-10-10 08:58 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +            @RequestParam(name = "id") Long id
`@RequestParam`으로 데이터를 받는 방식은 주로 필터링, 검색, 또는 정렬과 같은 선택적 쿼리 파라미터가 있을 때 사용됩니다. 예를 들어, 여러 **조건**으로 축제 목록을 조회하거나, 특정 필드를 기반으로 데이터를 **필터링**할 때 유용합니다.

그러나 이 경우는 특정 `festivalId`에 해당하는 자원의 일정을 조회하는 것이기 때문에, 자원을 명확히 식별하는 `@PathVariable`을 사용하는 것이 더 `RESTful`한 설계입니다. 따라서 `/api/v1/festivals/{festivalId}/active-period`로 변경하는 것을 추천드려요!

2024-10-10 08:58 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +public class FestivalDateController {
현재 `FestivalController`가 존재하는 것으로 알고 있는데, `FestivalDateController`를 따로 작성해주신 이유가 있는지 여쭤봐도 될까요?

2024-10-10 08:58 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/application/FestivalDateService.java
> +public class FestivalDateService {
추가적으로, `FestivalService`가 이미 존재하는데 `FestivalDateService`를 별도로 작성하신 이유가 궁금합니다!

2024-10-10 09:03 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalActivePeriodResponseDto.java
`FestivalActivePeriodResponseDto` 클래스를 잘 작성하셨어요! `@Builder` 어노테이션 덕분에 생성자가 더 읽기 쉬워졌고, `record` 타입을 사용해 `DTO`의 불변성을 잘 보장해주신 점이 마음에 듭니다 :)

2024-10-10 09:11 UTC, mungsil commented
추가로, PR을 작성하실 때 작업하신 API의 실행 결과, 즉 응답을 스크린샷으로 추가해주시면 리뷰어들이 작업 내용을 더 쉽게 이해할 수 있어요. 다음부터는 응답 결과도 함께 포함해주시면 좋을 것 같아요!

> _예시_
   ![image](https://github.com/user-attachments/assets/0d72378c-8094-4bf6-a81f-52fb953fb67e)

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/application/FestivalDateService.java
> +public class FestivalDateService {
1. UseCase 인터페이스 구현하도록 하겠습니다 !
2. 별도로 FestivalDateService를 작성한 이유는 조금이라도 역할이 다르면 나누는 게 낫지 않을까 싶기도 하고, 혹시 다른 팀원들의 코드와 섞일 까봐 일단 별도로 작성해둔 것입니다.  합치는 걸 원하시면 FestivalService에 합쳐놓겠습니당

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +public class FestivalDateController {
이것도 위의 service를 나눈 이유와 동일합니다 !
편하게 의견주세요

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +    private final FestivalDateService festivalDateService;
네 변경하겠습니다 !

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +            @RequestParam(name = "id") Long id
네 수정해두겠습니다 !

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +            @RequestParam(name = "id") Long id
혹시 /api/v1/festivals/{festivalId}/active-period 이 순서를 /api/v1/festivals/active-period/{festivalId} 이렇게 하지 않는 이유가 있을까요 ? 
이유가 있는 건지 단순히 궁금해서요 !

2024-10-11 05:28 UTC, nahyun0423 commented on src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalActivePeriodResponseDto.java
감사합니다 ^__^

2024-10-11 09:45 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/application/FestivalDateService.java
> +public class FestivalDateService {
축제 일정을 조회하는 기능은 Festival의 일정을 조회하는 기능이기 때문에, 따로 서비스 클래스를 작성하기보다 FestivalService에 작성하는게 더 관리가 쉬워요.
즉 Festival과 관련된 기능은 FestivalService에 작성해주시면 됩니다.
축제 일정과 관련된 기능이 일정을 조회하는 기능 한 가지이기 때문에, 일정 기능의 확장 가능성도 없는 것도 서비스 클래스를 따로 분리하지 않는 이유라고 말씀드릴 수 있을 것 같아요.

따라서 FestivalService에 합쳐서 작성해주시면 될 것 같습니다.

2024-10-11 09:47 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +public class FestivalDateController {
FestivalController에 작성해주시는게 더 좋을 것 같습니다!

2024-10-12 14:11 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalDateController.java
> +            @RequestParam(name = "id") Long id
`RESTful`한 설계에서는 주로 리소스의 계층 구조를 `URL`에 반영하는데, `/api/v1/festivals/{festivalId}/active-period`처럼 먼저 리소스(festivals)를 명시하고 그 리소스의 특정 데이터를 가져오는 방식이 더 자연스러워요. 즉, 해당 축제의 일정을 조회하는 것이니 축제(festivalId)를 먼저 지정하는 거에요.

반대로 `/api/v1/festivals/active-period/{festivalId}`로 하면, `active-period`가 마치 주요한 리소스처럼 보일 수 있어서 혼란을 줄 수 있거든요. 그래서 보통, 리소스를 먼저 두고 그 안의 세부적인 데이터를 접근하는 방식으로 많이 사용됩니다!

2024-10-12 15:07 UTC, mungsil requested changes

2024-10-12 15:07 UTC, mungsil commented on src/main/java/com/example/mohago_nocar/festival/presentation/FestivalController.java
> +    public ApiResponse<FestivalActivePeriodResponseDto> findFestivalDate(@PathVariable Long id) {
`@PathVariable Long id `대신에 `@PathVariable Long festivalId`로 수정 부탁드릴게요! 정상적인 코드 작동을 위해서는 `@GetMapping`에서의 `pathVariable` 이름과 파라미터 이름이 일치해야 합니다. 만약 이름을 다르게 사용하고 싶으시다면, `@PathVariable(name="festivalId")`처럼 `name` 속성을 명시해주시면 됩니다 :)

2024-10-14 07:21 UTC, mungsil approved these changes
확인 완료했습니다! 👍

2024-10-14 08:15 UTC, mingmingmon approved these changes

2024-10-14 08:16 UTC, merged